# Generated by Django 4.1.9 on 2023-05-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_accepted',
            field=models.BooleanField(default=False, help_text="Designates whether user's registration has been accepted by an admin."),
        ),
    ]
