# Generated by Django 4.1.9 on 2023-06-04 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.')),
                ('name', models.CharField(help_text='The name of the category.', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.')),
                ('title', models.CharField(help_text='The title of the post.', max_length=255)),
                ('body', models.TextField(help_text='The text body of the post.')),
                ('categories', models.ManyToManyField(help_text='The categories related to this post.', related_name='posts', to='blog.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.')),
                ('body', models.TextField(help_text='The text body of the comment.')),
                ('author', models.ForeignKey(help_text='The name of the author of the comment.', max_length=60, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(help_text='The post this comment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
