# Generated by Django 4.1.9 on 2023-06-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Enter the name of the technology.', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Enter a description of the technology.', null=True)),
            ],
            options={
                'verbose_name_plural': 'technologies',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Enter a description of the project.', null=True)),
                ('image', models.ImageField(blank=True, help_text='Add an image of the project.', null=True, upload_to='')),
                ('technology', models.ManyToManyField(help_text='Select a technology for this project.', related_name='projects', to='portfolio.technology', verbose_name='technologies')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
