# Generated by Django 4.1.9 on 2023-05-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Enter a description of the project.')),
                ('technology', models.CharField(help_text='Enter the technology used in the project.', max_length=30)),
                ('image', models.ImageField(help_text='Add an image of the project.', upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Enter the name of the technology.', max_length=30)),
                ('description', models.TextField(help_text='Enter a description of the technology.')),
                ('image', models.ImageField(help_text='Add an image of the technology.', upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
