# Generated by Django 4.1.9 on 2023-05-21 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Enter a description of the project.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(help_text='Add an image of the project.', path='/img'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(help_text='Enter the technology used in the project.', max_length=30),
        ),
    ]
