# Generated by Django 4.1.9 on 2023-05-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(help_text='Add an image of the project.', upload_to='static/media/images/'),
        ),
    ]
